"""add migration

Revision ID: 7b5704286242
Revises: 
Create Date: 2021-11-28 21:33:02.515293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5704286242'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorten_url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('shorten_token', sa.VARCHAR(length=8), nullable=False),
    sa.Column('number_click', sa.Integer(), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shorten_token')
    )
    op.create_index(op.f('ix_shorten_url_origin_url'), 'shorten_url', ['origin_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shorten_url_origin_url'), table_name='shorten_url')
    op.drop_table('shorten_url')
    # ### end Alembic commands ###
