"""add table url_click

Revision ID: acb53ad380cb
Revises: 7b5704286242
Create Date: 2021-11-29 21:59:32.484386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb53ad380cb'
down_revision = '7b5704286242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_click',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('shorten_token', sa.VARCHAR(length=8), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=55), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
    sa.Column('referer', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_click')
    # ### end Alembic commands ###
